# Generated by Django 3.1 on 2021-03-03 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='用户名'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('about', models.CharField(max_length=300, verbose_name='知识点')),
                ('content', models.CharField(max_length=500, verbose_name='题目描述')),
                ('answer', models.CharField(max_length=500, verbose_name='正确答案')),
                ('authority', models.CharField(choices=[('private', '私人'), ('public', '公共')], default='私人', max_length=10, verbose_name='题目权限')),
                ('finish_times', models.IntegerField(default=0, verbose_name='做题次数')),
                ('currect_times', models.IntegerField(default=0, verbose_name='正确次数')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('pic_url', models.CharField(max_length=500, verbose_name='图片地址')),
                ('type', models.CharField(choices=[('single', '单选题'), ('multiple', '多选题'), ('judge', '判断题'), ('programming', '编程题')], default='单选题', max_length=30, verbose_name='题目类型')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.user')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('content', models.CharField(max_length=500, verbose_name='选项内容')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('pic_url', models.CharField(max_length=500, verbose_name='图片地址')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.question')),
            ],
        ),
    ]
